# config_gpu.yaml
workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-8
    acceleratorType: NVIDIA_TESLA_T4
    acceleratorCount: 1
  replicaCount: 1
  containerSpec:
    imageUri: europe-west1-docker.pkg.dev/corded-smithy-484309-s4/g41-registry/train-cu128:latest
    env:
      - name: WANDB_API_KEY
        value: $WANDB_API_KEY
    args:
      - "experiment=best"
      - "training.save_checkpoint=false"
      - "training.enable_checkpointing=false"
