wandb_version: 1

seed:
  value: 42
training.accumulate_grad_batches:
  value: 1
training.batch_size:
  value: 64
training.gradient_clip_val:
  value: null
training.learning_rate:
  value: 5.535704827466145e-05
training.log_model:
  value: false
training.lr_scheduler.num_warmup_steps:
  value: 50
training.num_epochs:
  value: 5
training.patience:
  value: 3
training.weight_decay:
  value: 0.08696435955438289
wandb.mode:
  value: online
