wandb_version: 1

dataset:
  value: full
seed:
  value: 42
training.accumulate_grad_batches:
  value: 2
training.batch_size:
  value: 32
training.enable_checkpointing:
  value: false
training.gradient_clip_val:
  value: 0.5
training.learning_rate:
  value: 0.00018604094825818232
training.log_model:
  value: false
training.lr_scheduler.num_warmup_steps:
  value: 0
training.num_epochs:
  value: 5
training.patience:
  value: 3
training.weight_decay:
  value: 0.06078268208988383
wandb.mode:
  value: online
