wandb_version: 1

dataset:
  value: full
seed:
  value: 42
training.accumulate_grad_batches:
  value: 1
training.batch_size:
  value: 32
training.enable_checkpointing:
  value: false
training.gradient_clip_val:
  value: 0
training.learning_rate:
  value: 0.00029006820833841134
training.log_model:
  value: false
training.lr_scheduler.num_warmup_steps:
  value: 50
training.num_epochs:
  value: 5
training.patience:
  value: 3
training.weight_decay:
  value: 0.02923398946235958
wandb.mode:
  value: online
