wandb_version: 1

dataset:
  value: full
seed:
  value: 42
training.accumulate_grad_batches:
  value: 2
training.batch_size:
  value: 16
training.enable_checkpointing:
  value: false
training.gradient_clip_val:
  value: 0
training.learning_rate:
  value: 5.028391107120467e-05
training.log_model:
  value: false
training.lr_scheduler.num_warmup_steps:
  value: 100
training.num_epochs:
  value: 5
training.patience:
  value: 3
training.weight_decay:
  value: 0.06982774963365854
wandb.mode:
  value: online
