wandb_version: 1

dataset:
  value: full
seed:
  value: 42
training.accumulate_grad_batches:
  value: 1
training.batch_size:
  value: 32
training.enable_checkpointing:
  value: false
training.gradient_clip_val:
  value: 1
training.learning_rate:
  value: 0.00014314372764290677
training.log_model:
  value: false
training.lr_scheduler.num_warmup_steps:
  value: 100
training.num_epochs:
  value: 5
training.patience:
  value: 3
training.weight_decay:
  value: 0.02038217938760474
wandb.mode:
  value: online
