wandb_version: 1

dataset:
  value: full
seed:
  value: 42
training.batch_size:
  value: 32
training.enable_checkpointing:
  value: false
training.learning_rate:
  value: 0.0002710195155126088
training.log_model:
  value: false
training.num_epochs:
  value: 3
training.patience:
  value: 2
training.weight_decay:
  value: 0.06415030218129801
wandb.mode:
  value: online
