wandb_version: 1

dataset:
  value: full
seed:
  value: 42
training.accumulate_grad_batches:
  value: 2
training.batch_size:
  value: 64
training.gradient_clip_val:
  value: 1
training.learning_rate:
  value: 0.0004488083635263383
training.log_model:
  value: false
training.lr_scheduler.num_warmup_steps:
  value: 100
training.num_epochs:
  value: 5
training.patience:
  value: 3
training.weight_decay:
  value: 0.008471952059777788
wandb.mode:
  value: online
