# Corrupt MNIST dataset configuration
name: full
train_path: preprocessed/full_train.parquet
test_path: preprocessed/full_test.parquet
val_path: preprocessed/full_validation.parquet
# num_classes: 10
# input_shape: [1, 28, 28]

# Data augmentation (for future use)
augmentation:
  enabled: false
