name: small
train_path: ${paths.data_root}/preprocessed/small_train.parquet
test_path: ${paths.data_root}/preprocessed/small_test.parquet
val_path: ${paths.data_root}/preprocessed/small_validation.parquet
num_classes: 3
