wandb_version: 1

seed:
  value: 42
training.accumulate_grad_batches:
  value: 4
training.batch_size:
  value: 16
training.gradient_clip_val:
  value: 1
training.learning_rate:
  value: 0.0001593277148257715
training.log_model:
  value: false
training.lr_scheduler.num_warmup_steps:
  value: 100
training.num_epochs:
  value: 5
training.patience:
  value: 3
training.weight_decay:
  value: 0.06757270471753438
wandb.mode:
  value: online
