name: Auto Approve Renovate PRs
on: pull_request_target

jobs:
  approve:
    runs-on: ubuntu-latest
    # Only run if the PR was created by the Renovate bot
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
